# Generated by Django 5.1.6 on 2025-02-23 08:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QO', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reponseetudiantouverte',
            name='question_ouverte',
        ),
        migrations.RemoveField(
            model_name='reponseetudiantouverte',
            name='etudiant',
        ),
        migrations.RemoveField(
            model_name='reponseetudiantouverte',
            name='evaluation',
        ),
        migrations.RenameField(
            model_name='evaluation',
            old_name='support_cours',
            new_name='course_support',
        ),
        migrations.RenameField(
            model_name='evaluation',
            old_name='date_creation',
            new_name='creation_date',
        ),
        migrations.RenameField(
            model_name='evaluation',
            old_name='professeur',
            new_name='teacher',
        ),
        migrations.RenameField(
            model_name='evaluation',
            old_name='titre',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='contenu',
            new_name='content',
        ),
        migrations.RemoveField(
            model_name='question',
            name='temps',
        ),
        migrations.AddField(
            model_name='question',
            name='time',
            field=models.IntegerField(default=60, help_text='Time in seconds'),
        ),
        migrations.CreateModel(
            name='OpenQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_characters', models.IntegerField()),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='open_question', to='QO.question')),
            ],
        ),
        migrations.CreateModel(
            name='StudentOpenResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('free_response', models.TextField()),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='open_responses', to='QO.evaluation')),
                ('open_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='open_responses', to='QO.openquestion')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='QuestionOuverte',
        ),
        migrations.DeleteModel(
            name='ReponseEtudiantOuverte',
        ),
    ]
